package com.bionic.kvt.serviceapp.activities;

import android.app.AlertDialog;
import android.content.Context;
import android.content.DialogInterface;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.support.v4.app.LoaderManager;
import android.support.v4.content.AsyncTaskLoader;
import android.support.v4.content.Loader;
import android.text.InputType;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import android.widget.Toast;

import com.bionic.kvt.serviceapp.R;
import com.bionic.kvt.serviceapp.Session;
import com.bionic.kvt.serviceapp.db.DbUtils;
import com.bionic.kvt.serviceapp.helpers.MailHelper;
import com.bionic.kvt.serviceapp.utils.AppLog;
import com.bionic.kvt.serviceapp.utils.AppLogItem;
import com.bionic.kvt.serviceapp.utils.Utils;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.Image;
import com.lowagie.text.Phrase;
import com.lowagie.text.pdf.ColumnText;
import com.lowagie.text.pdf.PdfContentByte;
import com.lowagie.text.pdf.PdfReader;
import com.lowagie.text.pdf.PdfStamper;
import com.lowagie.text.pdf.PdfWriter;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;

import butterknife.BindView;
import butterknife.ButterKnife;
import butterknife.OnClick;
import io.realm.Realm;
import io.realm.RealmChangeListener;
import io.realm.RealmResults;

import static com.bionic.kvt.serviceapp.GlobalConstants.ORDER_STATUS_COMPLETE;
import static com.bionic.kvt.serviceapp.GlobalConstants.PDF_PASSWORD;
import static com.bionic.kvt.serviceapp.GlobalConstants.PDF_REPORT_FILE_NAME;

/**
 * An activity for final PDF Report preview.<br>
 * Started by {@link SignaturesActivity}.<br>
 * Next activity {@link OrderPageActivity}.
 * <p/>
 * Generate final PDF Report.<br>
 * Set order status as {@link com.bionic.kvt.serviceapp.GlobalConstants#ORDER_STATUS_COMPLETE}.<br>
 * Use PDF Report preview generated by {@link PDFReportPreviewActivity}.<br>
 * Generate PDF Report file in current order folder: {@link Utils#getOrderDir(long)}.<br>
 * Preview file is deleted.
 */

public class PDFReportActivity extends BaseActivity implements LoaderManager.LoaderCallbacks<Boolean> {
    private static final String ROTATION_FLAG = "ROTATION_FLAG";
    private static final int PDF_LOADER_ID = 1;
    private static final int MAIL_LOADER_ID = 2;
    private MailHelper mailHelper;
    private File pdfReportFile;
    private File pdfReportPreviewFile;

    private String engineerName;
    private String clientName;

    private AlertDialog enterEmailDialog;

    // App Log monitor
    private Realm monitorLogRealm = Session.getLogRealm();
    private RealmChangeListener<RealmResults<AppLogItem>> logListener;
    private RealmResults<AppLogItem> logsWithNotification;

    @BindView(R.id.pdf_report_send_button)
    Button sendButton;

    @BindView(R.id.pdf_text_log)
    TextView pdfTextLog;

    @BindView(R.id.pdf_report_bottom)
    LinearLayout reportBottomLayout;

    @BindView(R.id.pdf_bitmap)
    ImageView pdfView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_pdf_report);
        ButterKnife.bind(this);

        android.support.v7.app.ActionBar actionBar = getSupportActionBar();
        if (actionBar != null) actionBar.setSubtitle(getText(R.string.pdf_report));

        // Setting App log listener
        logListener = AppLog.setLogListener(PDFReportActivity.this, monitorLogRealm);
        logsWithNotification = AppLog.addListener(monitorLogRealm, logListener);

        // Exit if Session is empty
        if (Session.getCurrentOrder() <= 0L) {
            AppLog.E(this, "No order number.");
            // Give time to read message
            final Handler handler = new Handler();
            handler.postDelayed(new Runnable() {
                public void run() {
                    final Intent intent = new Intent(PDFReportActivity.this, OrderPageActivity.class);
                    intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);
                    startActivity(intent);
                }
            }, 3000);
            return;
        }

        AppLog.serviceI(false, Session.getCurrentOrder(), "Create activity: " + PDFReportActivity.class.getSimpleName());

        final Bundle extras = getIntent().getExtras();
        if (extras != null) {
            engineerName = extras.getString("ENGINEER_NAME");
            clientName = extras.getString("CLIENT_NAME");
        }

        final long orderNumber = Session.getCurrentOrder();

        final String pdfReportFileName = getText(R.string.generating_pdf_document).toString()
                + " " + PDF_REPORT_FILE_NAME + orderNumber + ".pdf";
        pdfTextLog.setText(pdfReportFileName);

        pdfReportFile = Utils.getPDFReportFileName(orderNumber, false);

        if (DbUtils.getOrderStatus(orderNumber) >= ORDER_STATUS_COMPLETE) {
            reportBottomLayout.setVisibility(View.GONE);
            if (pdfReportFile.exists()) { // We have report.
                sendButton.setEnabled(true);
                Utils.showPDFReport(this, pdfReportFile, pdfView);
            } else {
                AppLog.E(this, "No PDF Report file: " + pdfReportFile.toString());
            }

            return;
        }

        // Check rotation
        if (savedInstanceState != null) {
            if (savedInstanceState.getBoolean(ROTATION_FLAG)) {
                // Device is rotated. No need to generate. Just show.
                sendButton.setEnabled(true);
                Utils.showPDFReport(this, pdfReportFile, pdfView);
                return;
            }
        }

        // Generating...
        if (pdfReportFile.exists()) { // Deleting old Report if exist
            pdfReportFile.delete();
        }

        pdfReportPreviewFile = Utils.getPDFReportFileName(orderNumber, true);
        if (!pdfReportPreviewFile.exists()) {
            AppLog.E(this, "Can not get pdf preview file.");
            return;
        }

        getSupportLoaderManager().initLoader(PDF_LOADER_ID, null, this);
    }

    @Override
    public Loader<Boolean> onCreateLoader(int id, Bundle args) {
        if (id == PDF_LOADER_ID)
            return new GeneratePDFReportFile(this, pdfReportFile, pdfReportPreviewFile, engineerName, clientName);
        if (id == MAIL_LOADER_ID)
            return new MailHelper.SendMail(this, mailHelper);
        return null;
    }

    @Override
    public void onLoadFinished(Loader<Boolean> loader, Boolean data) {
        switch (loader.getId()) {
            case PDF_LOADER_ID:
                sendButton.setEnabled(true);
                Utils.showPDFReport(this, pdfReportFile, pdfView);
                break;
            case MAIL_LOADER_ID:
                if (data) {
                    Toast.makeText(this,
                            getText(R.string.success_email_toast), Toast.LENGTH_SHORT).show();
                } else {
                    Toast.makeText(this,
                            getText(R.string.error_email_toast), Toast.LENGTH_SHORT).show();
                }
                break;
        }
    }

    @Override
    public void onLoaderReset(Loader<Boolean> loader) {
        // NOOP
    }

    public static class GeneratePDFReportFile extends AsyncTaskLoader<Boolean> {
        private final int pdfPageCount = 1;
        private final File pdfReportFile;
        private final File pdfReportPreviewFile;
        private final String engineerName;
        private final String clientName;

        public GeneratePDFReportFile(final Context context,
                                     final File pdfReportFile,
                                     final File pdfReportPreviewFile,
                                     final String engineerName,
                                     final String clientName) {
            super(context);
            this.pdfReportFile = pdfReportFile;
            this.pdfReportPreviewFile = pdfReportPreviewFile;
            this.engineerName = engineerName;
            this.clientName = clientName;
        }

        @Override
        public void forceLoad() {
            super.forceLoad();
        }

        @Override
        protected void onStartLoading() {
            super.onStartLoading();
            forceLoad();
        }

        @Override
        protected void onStopLoading() {
            super.onStopLoading();
        }

        @Override
        public void deliverResult(Boolean data) {
            super.deliverResult(data);
        }

        @Override
        public Boolean loadInBackground() {
            try {
                final PdfReader pdfReader = new PdfReader(pdfReportPreviewFile.toString());
                final PdfStamper pdfStamper = new PdfStamper(pdfReader, new FileOutputStream(pdfReportFile));
                pdfStamper.setEncryption(null,
                        PDF_PASSWORD.getBytes(),
                        PdfWriter.ALLOW_PRINTING,
                        PdfWriter.STANDARD_ENCRYPTION_128);
                final Font font = new Font(Font.HELVETICA, 11, Font.NORMAL);
                final PdfContentByte contentByte = pdfStamper.getOverContent(pdfPageCount);
                final ColumnText columnText = new ColumnText(contentByte);

                Phrase orderText7 = new Phrase(engineerName, font);
                int x = 355;
                int y = 56;
                columnText.setSimpleColumn(orderText7, x, y, x + 150, y + 25, 21.8f, Element.ALIGN_LEFT);
                columnText.go();

                Phrase orderText8 = new Phrase(clientName, font);
                x = 120;
                y = 56;
                columnText.setSimpleColumn(orderText8, x, y, x + 150, y + 25, 21.8f, Element.ALIGN_LEFT);
                columnText.go();

                Image signatureEngineer = Image.getInstance(Session.getByteArrayEngineerSignature());
                signatureEngineer.setAbsolutePosition(325f, 79f);
                signatureEngineer.scaleAbsolute(192, 74);
                contentByte.addImage(signatureEngineer);

                Image signatureClient = Image.getInstance(Session.getByteArrayClientSignature());
                signatureClient.setAbsolutePosition(102f, 79f);
                signatureClient.scaleAbsolute(192, 74);
                contentByte.addImage(signatureClient);

                pdfStamper.close();
            } catch (IOException | DocumentException e) {
                AppLog.serviceE(true, Session.getCurrentOrder(), "Error while generating PDF: " + e.toString());
            }

            return false;
        }
    }

    @Override
    protected void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        outState.putBoolean(ROTATION_FLAG, true);
    }

    @Override
    protected void onStop() {
        super.onStop();
        if (enterEmailDialog != null && enterEmailDialog.isShowing()) enterEmailDialog.dismiss();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        AppLog.removeListener(monitorLogRealm, logsWithNotification, logListener);
    }

    @OnClick(R.id.pdf_button_complete_order)
    public void onDoneClick(View v) {
        DbUtils.setOrderStatus(Session.getCurrentOrder(), ORDER_STATUS_COMPLETE);
        Utils.updateOrderStatusOnServer(Session.getCurrentOrder());

        // Cleaning
        if (pdfReportPreviewFile != null) pdfReportPreviewFile.delete();
        Session.setByteArrayClientSignature(null);
        Session.setByteArrayEngineerSignature(null);

        final Intent intent = new Intent(PDFReportActivity.this, OrderPageActivity.class);
        intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);
        startActivity(intent);
    }

    @OnClick(R.id.pdf_report_send_button)
    public void onSendClick(View v) {
        final AlertDialog.Builder dialogBuilder = new AlertDialog.Builder(this);
        dialogBuilder.setTitle(getText(R.string.email_dialog_title));
        final EditText emailEdit = new EditText(this);
        emailEdit.setInputType(InputType.TYPE_CLASS_TEXT | InputType.TYPE_TEXT_VARIATION_EMAIL_ADDRESS);
        emailEdit.setText(Session.getEngineerEmail());
        dialogBuilder.setView(emailEdit);

        dialogBuilder.setPositiveButton("OK", new DialogInterface.OnClickListener() {
            @Override
            public void onClick(DialogInterface dialog, int which) {
                sendEmailWithPDF(emailEdit.getText().toString());
                dialog.dismiss();
            }
        });
        dialogBuilder.setNegativeButton("Cancel", new DialogInterface.OnClickListener() {
            @Override
            public void onClick(DialogInterface dialog, int which) {
                dialog.cancel();
            }
        });

        enterEmailDialog = dialogBuilder.create();
        enterEmailDialog.show();
    }

    public void sendEmailWithPDF(final String email) {
        mailHelper = new MailHelper();
        mailHelper.setRecipient(email);
        mailHelper.setMessageBody("This is a PDF report");
        mailHelper.setSubject("PDF_Report");
        mailHelper.setFullFileName(pdfReportFile.toString());

        getSupportLoaderManager().restartLoader(MAIL_LOADER_ID, null, this);
    }
}



